// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Oracle2023Ddd.Infra.Data.Contexts.TmsDb;

#nullable disable

namespace Oracle2023Ddd.Infra.Data.Contexts.TmsDb.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20240130161810_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_CLIENT")
                .HasMax(2147483647L);

            modelBuilder.HasSequence<int>("SEQ_ENDERE")
                .HasMax(2147483647L);

            modelBuilder.HasSequence<int>("SEQ_PESSOA")
                .HasMax(2147483647L);
#pragma warning restore 612, 618
        }
    }
}
