// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Oracle2023Ddd.Infra.Data.Contexts.TmsDb;

#nullable disable

namespace Oracle2023Ddd.Infra.Data.Contexts.TmsDb.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20240130162156_V1.0.0")]
    partial class V100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_CLIENT")
                .HasMax(2147483647L);

            modelBuilder.HasSequence<int>("SEQ_ENDERE")
                .HasMax(2147483647L);

            modelBuilder.HasSequence<int>("SEQ_PESSOA")
                .HasMax(2147483647L);

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_IDENTI");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDb")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ATIVO");

                    b.Property<DateTime>("BeginningDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATINI");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_CEP");

                    b.Property<string>("ChangedDb")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ALTEND");

                    b.Property<string>("City")
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_CIDADE");

                    b.Property<int>("CityId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_LOC_IDENTI");

                    b.Property<string>("Country")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_PAIS");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_CPA_PAIS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATCRI");

                    b.Property<string>("CreatorProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_PRGCRI");

                    b.Property<int>("CreatorUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_USUCRI");

                    b.Property<string>("District")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_BAIRRO");

                    b.Property<DateTime?>("EndingDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATFIM");

                    b.Property<string>("IbgeCity")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_IBGECI");

                    b.Property<int?>("IbgeCountry")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_IBGEPA");

                    b.Property<int?>("IbgeUf")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_IBGEUF");

                    b.Property<int?>("IdPerson")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_PES_IDENTI");

                    b.Property<string>("Number")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_NUMERO");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ORIGEM");

                    b.Property<int?>("ParentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_EDE_IDENTI");

                    b.Property<string>("RedispatchDescription")
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_REDESP");

                    b.Property<DateTime?>("RestrictWindowDeliveryBegin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HOINNA");

                    b.Property<DateTime?>("RestrictWindowDeliveryFinal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HOFINA");

                    b.Property<string>("State")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ESTADO");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ENDERE");

                    b.Property<string>("Supplement")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_COMPLE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_TIPEDE");

                    b.Property<string>("TypeAddress")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_TIPLOG");

                    b.Property<string>("UnitFederationCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_UNF_UNIFED");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_PRGALT");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_USUALT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATALT");

                    b.Property<string>("UserBdd")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_USUBDD");

                    b.Property<DateTime?>("WindowDeliveryBegin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HORINI");

                    b.Property<DateTime?>("WindowDeliveryFinal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HORLIM");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson");

                    b.ToTable("TMS_ENDERE", (string)null);
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Cnae", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_CNAE")
                        .HasColumnOrder(1);

                    b.Property<string>("ChapterNcm")
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_CAPNCM");

                    b.Property<string>("Class")
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_CLASSE");

                    b.Property<string>("CodeParent")
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_RELAC");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CNA_DATCRI");

                    b.Property<string>("CreatorProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_PRGCRI");

                    b.Property<int>("CreatorUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CNA_USUCRI");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_DESCRI");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_DIVISA");

                    b.Property<string>("Group")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_GRUPO");

                    b.Property<string>("IdActivity")
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_ATIVID");

                    b.Property<string>("Section")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_SECAO");

                    b.Property<string>("SubClass")
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_SUBCLA");

                    b.Property<string>("UpdateProgram")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_PRGALT");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CNA_USUALT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CNA_DATALT");

                    b.Property<string>("UserBdd")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CNA_USUBDD");

                    b.HasKey("Id");

                    b.ToTable("TMS_CNAE", (string)null);
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_IDENTI");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDb")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_ATIVO");

                    b.Property<int?>("AddressIdMain")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_EDE_IDENTI_PRINCI");

                    b.Property<string>("CommercialClassification")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_CLACOM");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLI_DATCRI");

                    b.Property<string>("CreatorProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CLI_PRGCRI");

                    b.Property<int>("CreatorUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_USUCRI");

                    b.Property<string>("CustomerClassification")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_CLACLI");

                    b.Property<string>("EstablishmentType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_ESPEST");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_CODEXT");

                    b.Property<string>("FiscalStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_SITFIS");

                    b.Property<int>("IdCompany")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_EMP_IDENTI");

                    b.Property<int>("IdPerson")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_PES_IDENTI");

                    b.Property<int>("IdTaxZone")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_ZTB_IDENTI");

                    b.Property<int?>("IdUnit")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_UNI_IDENTI");

                    b.Property<int?>("IdUnitLinked")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_UNI_IDENTI_VINCUL");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLI_DATCAD");

                    b.Property<int>("RegisterSource")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_ORICAD");

                    b.Property<string>("RegisterSourceDb")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("SearchDateWS")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLI_DATCON");

                    b.Property<int?>("SectorLogisticId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_CLG_IDENTI");

                    b.Property<string>("SituationDescriptionWS")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_SITDES");

                    b.Property<string>("SituationWSDb")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_SITREC");

                    b.Property<string>("TaxpayerClassificationSystem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_REGAPU");

                    b.Property<string>("TaxpayerType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLI_TIPCTR");

                    b.Property<string>("UpdateProgram")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CLI_PRGALT");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLI_USUALT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLI_DATALT");

                    b.Property<string>("UserBdd")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("CLI_USUBDD");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson");

                    b.ToTable("TMS_CLIENT", (string)null);
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_IDENTI");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CnaeDescription")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESCNA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PES_DATCRI");

                    b.Property<string>("CreatorProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_PRGCRI");

                    b.Property<int>("CreatorUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_USUCRI");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESCRI");

                    b.Property<string>("FictitiousName")
                        .HasMaxLength(65)
                        .HasColumnType("NVARCHAR2(65)")
                        .HasColumnName("PES_NOMFAN");

                    b.Property<string>("IdCnae")
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_CNA_CNAE");

                    b.Property<string>("ReductedDescription")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESRED");

                    b.Property<string>("RegionalIdRegistration")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_INSMUN");

                    b.Property<string>("StadualIdRegistration")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_INSEST");

                    b.Property<int?>("SysRevisa")
                        .IsRequired()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYS_REVISA");

                    b.Property<string>("TaxIdRegistration")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_CPFCNP");

                    b.Property<string>("TypePersonDb")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_TIPPES");

                    b.Property<string>("UpdateProgram")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_PRGALT");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_USUALT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PES_DATALT");

                    b.Property<string>("UserBdd")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_USUBDD");

                    b.HasKey("Id");

                    b.HasIndex("IdCnae")
                        .HasDatabaseName("FK_TMS_CNAE_CNA_CNAE");

                    b.ToTable("TMS_PESSOA", (string)null);
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Address", b =>
                {
                    b.HasOne("Oracle2023Ddd.Domain.TmsContext.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("IdPerson")
                        .HasConstraintName("FK_EDE_PES_IDENTI");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Customer", b =>
                {
                    b.HasOne("Oracle2023Ddd.Domain.TmsContext.Entities.Person", "Person")
                        .WithMany("Customers")
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CLI_PES_IDENTI");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Person", b =>
                {
                    b.HasOne("Oracle2023Ddd.Domain.TmsContext.Entities.Cnae", "Cnae")
                        .WithMany("People")
                        .HasForeignKey("IdCnae")
                        .HasConstraintName("FK_PES_CNA_CNAE");

                    b.Navigation("Cnae");
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Cnae", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("Oracle2023Ddd.Domain.TmsContext.Entities.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
