// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Rte2023Ddd.Infra.Data.Contexts.TmsDb;

#nullable disable

namespace Rte2023Ddd.Infra.Data.Contexts.TmsDb.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20231113155651_V0.0.2")]
    partial class V002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_ENDERE")
                .HasMax(2147483647L);

            modelBuilder.HasSequence<int>("SEQ_PESSOA")
                .HasMax(2147483647L);

            modelBuilder.Entity("Rte2023Ddd.Domain.TmsContext.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_IDENTI");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDb")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ATIVO");

                    b.Property<DateTime>("BeginningDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATINI");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_CEP");

                    b.Property<string>("ChangedDb")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ALTEND");

                    b.Property<string>("City")
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_CIDADE");

                    b.Property<int>("CityId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_LOC_IDENTI");

                    b.Property<string>("Country")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_PAIS");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_CPA_PAIS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATCRI");

                    b.Property<string>("CreatorProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_PRGCRI");

                    b.Property<int>("CreatorUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_USUCRI");

                    b.Property<string>("District")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_BAIRRO");

                    b.Property<DateTime?>("EndingDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATFIM");

                    b.Property<string>("IbgeCity")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_IBGECI");

                    b.Property<int?>("IbgeCountry")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_IBGEPA");

                    b.Property<int?>("IbgeUf")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_IBGEUF");

                    b.Property<int?>("IdPerson")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_PES_IDENTI");

                    b.Property<string>("Number")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_NUMERO");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ORIGEM");

                    b.Property<int?>("ParentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_EDE_IDENTI");

                    b.Property<string>("RedispatchDescription")
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_REDESP");

                    b.Property<DateTime?>("RestrictWindowDeliveryBegin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HOINNA");

                    b.Property<DateTime?>("RestrictWindowDeliveryFinal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HOFINA");

                    b.Property<string>("State")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ESTADO");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_ENDERE");

                    b.Property<string>("Supplement")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_COMPLE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_TIPEDE");

                    b.Property<string>("TypeAddress")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_TIPLOG");

                    b.Property<string>("UnitFederationCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_UNF_UNIFED");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_PRGALT");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EDE_USUALT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_DATALT");

                    b.Property<string>("UserBdd")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("EDE_USUBDD");

                    b.Property<DateTime?>("WindowDeliveryBegin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HORINI");

                    b.Property<DateTime?>("WindowDeliveryFinal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EDE_HORLIM");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson")
                        .HasDatabaseName("IX_ENDERE_EDE_PES_IDENTI");

                    b.ToTable("TMS_ENDERE", (string)null);
                });

            modelBuilder.Entity("Rte2023Ddd.Domain.TmsContext.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_IDENTI");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnae")
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_CNA_CNAE");

                    b.Property<string>("CnaeDescription")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESCNA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PES_DATCRI");

                    b.Property<string>("CreatorProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_PRGCRI");

                    b.Property<int>("CreatorUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_USUCRI");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESCRI");

                    b.Property<string>("FictitiousName")
                        .HasMaxLength(65)
                        .HasColumnType("NVARCHAR2(65)")
                        .HasColumnName("PES_NOMFAN");

                    b.Property<string>("ReductedDescription")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESRED");

                    b.Property<string>("RegionalIdRegistration")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_INSMUN");

                    b.Property<string>("StadualIdRegistration")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_INSEST");

                    b.Property<int?>("SysRevisa")
                        .IsRequired()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYS_REVISA");

                    b.Property<string>("TaxIdRegistration")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_CPFCNP");

                    b.Property<int>("TypePerson")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TypePersonDb")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_TIPPES");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_PRGALT");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_USUALT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PES_DATALT");

                    b.Property<string>("UserBdd")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_USUBDD");

                    b.HasKey("Id");

                    b.ToTable("TMS_PESSOA", (string)null);
                });

            modelBuilder.Entity("Rte2023Ddd.Domain.TmsContext.Entities.Address", b =>
                {
                    b.HasOne("Rte2023Ddd.Domain.TmsContext.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("IdPerson")
                        .HasConstraintName("FK_EDE_PES_IDENTI");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Rte2023Ddd.Domain.TmsContext.Entities.Person", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
