// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Rte2023Ddd.Infra.Data.Contexts.TmsDb;

#nullable disable

namespace Rte2023Ddd.Infra.Data.Contexts.TmsDb.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20231113154309_V0.0.1")]
    partial class V001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_PESSOA")
                .HasMax(2147483647L);

            modelBuilder.Entity("Rte2023Ddd.Domain.TmsContext.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_IDENTI");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnae")
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_CNA_CNAE");

                    b.Property<string>("CnaeDescription")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESCNA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PES_DATCRI");

                    b.Property<string>("CreatorProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_PRGCRI");

                    b.Property<int>("CreatorUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_USUCRI");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESCRI");

                    b.Property<string>("FictitiousName")
                        .HasMaxLength(65)
                        .HasColumnType("NVARCHAR2(65)")
                        .HasColumnName("PES_NOMFAN");

                    b.Property<string>("ReductedDescription")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_DESRED");

                    b.Property<string>("RegionalIdRegistration")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_INSMUN");

                    b.Property<string>("StadualIdRegistration")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_INSEST");

                    b.Property<int?>("SysRevisa")
                        .IsRequired()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYS_REVISA");

                    b.Property<string>("TaxIdRegistration")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_CPFCNP");

                    b.Property<int>("TypePerson")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TypePersonDb")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_TIPPES");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_PRGALT");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PES_USUALT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PES_DATALT");

                    b.Property<string>("UserBdd")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("PES_USUBDD");

                    b.HasKey("Id");

                    b.ToTable("TMS_PESSOA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
